/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userInterface.DoctorRole;

import Business.Employee.Employee;
import Business.Enterprise.HospitalEnterprise;
import Business.Patient.PatientVisit;
import Business.Patient.PatientVisitDirectory;
import DatabaseUtility.DatabaseHandleHospitalRoles;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class DoctorManagePatientsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorManagePatientsJPanel
     */
    Employee emp;
    int doctorId;
    Boolean rowSelected=false;
    PatientVisitDirectory pvd = new PatientVisitDirectory();
    DatabaseHandleHospitalRoles dbCon;
    ArrayList<Employee> pathoList;
    public DoctorManagePatientsJPanel(Employee e) {
        initComponents();
        this.emp=e;
        this.doctorId=emp.getId();
        dbCon=new DatabaseHandleHospitalRoles();
//        System.out.println("Doctor Id" + doctorId);
        populatePatients(dbCon.fetchPatientsDoctor(doctorId)); 
        jTextNamePatient.setEditable(false);
        jTextPatientType.setEditable(false);
        pathoList=dbCon.fetchPatho(doctorId); // All available doctors in the hospital;
        populatePathoList(pathoList);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableManagePateints = new javax.swing.JTable();
        jButtonViewPatient = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextNamePatient = new javax.swing.JTextField();
        jTextPatientType = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextPatientTemperature = new javax.swing.JTextField();
        jTextPatientPulse = new javax.swing.JTextField();
        jTextPatientBP = new javax.swing.JTextField();
        jTextRespirationRate = new javax.swing.JTextField();
        jButtonSavePatients = new javax.swing.JButton();
        jButtonFetchPathoReport = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextPatientBloodType = new javax.swing.JTextField();
        jTextPatientTissueType = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextPatientHeight = new javax.swing.JTextField();
        jTextPatientWeight = new javax.swing.JTextField();
        jButtonUpdateStatus = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jComboPatientStatus = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jComboBoxPatho = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));

        jTableManagePateints.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTableManagePateints.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NAME", "TYPE", "DATE", "PATHO STATUS", "ELIGIBILITY STATUS"
            }
        ));
        jScrollPane1.setViewportView(jTableManagePateints);

        jButtonViewPatient.setText("VIEW PATIENT");
        jButtonViewPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewPatientActionPerformed(evt);
            }
        });

        jLabel1.setText("NAME");

        jLabel2.setText("TYPE");

        jLabel5.setText("TEMPERATURE");

        jLabel6.setText("PULSE");

        jLabel7.setText("BP");

        jLabel8.setText("RESPIRATION RATE");

        jButtonSavePatients.setText("SAVE DETAILS AND REQUEST PATHO REPORT");
        jButtonSavePatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSavePatientsActionPerformed(evt);
            }
        });

        jButtonFetchPathoReport.setText("FETCH PATHO DETAILS");

        jLabel10.setText("BLOOD TYPE");

        jLabel11.setText("TISSUE TYPE");

        jLabel12.setText("WEIGHT");

        jLabel13.setText("HEIGHT");

        jButtonUpdateStatus.setText("UPDATE STATUS");
        jButtonUpdateStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateStatusActionPerformed(evt);
            }
        });

        jLabel9.setText("ELIGIBILITY STATUS");

        jComboPatientStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YES", "NO" }));

        jLabel14.setText("PATHOLOGIST");

        jComboBoxPatho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonViewPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(530, 530, 530))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(jButtonSavePatients, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(jTextPatientType, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                                                    .addComponent(jTextNamePatient, javax.swing.GroupLayout.Alignment.LEADING)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextPatientWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addGap(47, 47, 47))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addGap(29, 29, 29)
                                                            .addComponent(jLabel5))
                                                        .addComponent(jLabel8)))
                                                .addGap(35, 35, 35))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(20, 20, 20)
                                        .addComponent(jTextPatientHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(62, 62, 62)
                                        .addComponent(jLabel14)
                                        .addGap(59, 59, 59)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextPatientTemperature)
                                    .addComponent(jTextPatientPulse)
                                    .addComponent(jTextPatientBP)
                                    .addComponent(jTextRespirationRate, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxPatho, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonFetchPathoReport, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextPatientTissueType, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                                    .addComponent(jTextPatientBloodType))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jButtonUpdateStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboPatientStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(148, 148, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonViewPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jButtonFetchPathoReport, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextNamePatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)
                                    .addComponent(jTextPatientBloodType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel12)
                                            .addComponent(jTextPatientWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTextPatientType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel11)
                                            .addComponent(jTextPatientTissueType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jTextPatientTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jTextPatientPulse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextPatientBP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(jTextRespirationRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jTextPatientHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jComboPatientStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                .addComponent(jButtonUpdateStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButtonSavePatients, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jComboBoxPatho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(150, 150, 150))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonViewPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewPatientActionPerformed
        // TODO add your handling code here:
        int selsctedIndex=jTableManagePateints.getSelectedRow();
        if (selsctedIndex != -1){
            rowSelected=true;
            jTextNamePatient.setText(jTableManagePateints.getValueAt(selsctedIndex, 1).toString());
            jTextPatientType.setText(jTableManagePateints.getValueAt(selsctedIndex, 2).toString()); 
            //Set value if set by doctor
            
        }
        else{
            JOptionPane.showMessageDialog(this, "Please select a row to fetch.");
        }
        
    }//GEN-LAST:event_jButtonViewPatientActionPerformed

    private void jButtonSavePatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSavePatientsActionPerformed
        // TODO add your handling code here:
        //Validation 
        if (rowSelected){
            int selectedIndex=jTableManagePateints.getSelectedRow();
            if (selectedIndex != -1){
            int visitId=Integer.parseInt(jTableManagePateints.getValueAt(selectedIndex, 0).toString());
            jTextNamePatient.setText(jTableManagePateints.getValueAt(selectedIndex, 1).toString());
            jTextPatientType.setText(jTableManagePateints.getValueAt(selectedIndex, 2).toString());
            float weight=Float.parseFloat(jTextPatientWeight.getText());
            float height=Float.parseFloat(jTextPatientHeight.getText());
            float temp=Float.parseFloat(jTextPatientTemperature.getText());
            int pulse=Integer.parseInt(jTextPatientPulse.getText());
            int bp=Integer.parseInt(jTextPatientBP.getText());
            int respRate=Integer.parseInt(jTextRespirationRate.getText());
            int pathoIndex=jComboBoxPatho.getSelectedIndex();
            int pathoId=pathoList.get(pathoIndex).getId();
            Boolean status=dbCon.creatVitals(visitId, weight, height, temp, pulse, bp, respRate,pathoId);
            if (status){
                JOptionPane.showMessageDialog(this, "Vitals Created.");
                jTextNamePatient.setText("");
                jTextPatientType.setText("");
                jTextPatientWeight.setText("");
                jTextPatientHeight.setText("");
                jTextPatientTemperature.setText("");
                jTextPatientPulse.setText("");
                jTextPatientBP.setText("");
                jTextRespirationRate.setText("");
                rowSelected=false;
                populatePatients(dbCon.fetchPatientsDoctor(doctorId));
            }
            else{
            JOptionPane.showMessageDialog(this, "Error in creating vitals");
            }
        }
        
        }else{
            JOptionPane.showMessageDialog(this, "Please select a row to fetch.");
        }
    }//GEN-LAST:event_jButtonSavePatientsActionPerformed

    private void jButtonUpdateStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateStatusActionPerformed
        // TODO add your handling code here:
        if (rowSelected){
            int selectedIndex=jTableManagePateints.getSelectedRow();
            if (selectedIndex != -1){
            int visitId=Integer.parseInt(jTableManagePateints.getValueAt(selectedIndex, 0).toString());
            jTextNamePatient.setText(jTableManagePateints.getValueAt(selectedIndex, 1).toString());
            jTextPatientType.setText(jTableManagePateints.getValueAt(selectedIndex, 2).toString());
            String type=jTableManagePateints.getValueAt(selectedIndex, 2).toString();
            int organStatus=0;
            String approval=jComboPatientStatus.getSelectedItem().toString();
            if (approval.equalsIgnoreCase("Yes")){
                organStatus=1;  
            }
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("uuuu/MM/dd");
            LocalDate localDate = LocalDate.now();
            String date=dtf.format(localDate);
                Boolean status = dbCon.updateDoctorApproval(visitId,organStatus,type,doctorId,date);
                if (status){
                    JOptionPane.showMessageDialog(this, "Patient added to the list and sent for admin approval.");
                     jTextNamePatient.setText("");
                    jTextPatientType.setText("");
                }
                else{
                    JOptionPane.showMessageDialog(this, "Error in approval");
                }
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Please select a row to fetch.");
        }
            
    }//GEN-LAST:event_jButtonUpdateStatusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFetchPathoReport;
    private javax.swing.JButton jButtonSavePatients;
    private javax.swing.JButton jButtonUpdateStatus;
    private javax.swing.JButton jButtonViewPatient;
    private javax.swing.JComboBox<String> jComboBoxPatho;
    private javax.swing.JComboBox<String> jComboPatientStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableManagePateints;
    private javax.swing.JTextField jTextNamePatient;
    private javax.swing.JTextField jTextPatientBP;
    private javax.swing.JTextField jTextPatientBloodType;
    private javax.swing.JTextField jTextPatientHeight;
    private javax.swing.JTextField jTextPatientPulse;
    private javax.swing.JTextField jTextPatientTemperature;
    private javax.swing.JTextField jTextPatientTissueType;
    private javax.swing.JTextField jTextPatientType;
    private javax.swing.JTextField jTextPatientWeight;
    private javax.swing.JTextField jTextRespirationRate;
    // End of variables declaration//GEN-END:variables

    private void populatePatients(ArrayList<PatientVisit> patientVisits) {
        DefaultTableModel model=(DefaultTableModel) jTableManagePateints.getModel();
        model.setRowCount(0);
        for (PatientVisit v: patientVisits)
        {
            Object[] row =new Object[7];
            row[0]=v.getId();
            row[1]=v.getName();
            row[2]=v.getType();
            row[3]=v.getDate();
            row[4]=v.getReportStatus();
            row[5]=v.getVitalStatus();
            
            model.addRow(row);
        }
    }

    private void populatePathoList(ArrayList<Employee> emp){
    for(Employee e:emp){
        jComboBoxPatho.addItem(e.getName());
    }
        
    }
}
