/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userInterface.Transport;

import Business.Employee.Employee;
import DatabaseUtility.DatabaseHandelTransportRoles;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class DriverStatusJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DriverStatusJPanel
     */
    Employee emp;
    int adminId;
    ArrayList <Employee> employeeList;
    DatabaseHandelTransportRoles dbCon=new DatabaseHandelTransportRoles();
    public DriverStatusJPanel(Employee e) {
        initComponents();
        this.emp=e;
        this.adminId=emp.getId();
        populateTable(dbCon.employeeList(adminId));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDriverAvailibilityStatus = new javax.swing.JTable();
        jButtonRefreshDriver = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jTableDriverAvailibilityStatus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "DRIVER ID", "DRIVER NAME", "DRIVER AVAIBILITY STATUS"
            }
        ));
        jScrollPane1.setViewportView(jTableDriverAvailibilityStatus);

        jButtonRefreshDriver.setBackground(new java.awt.Color(175, 38, 72));
        jButtonRefreshDriver.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRefreshDriver.setText("REFERESH");
        jButtonRefreshDriver.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButtonRefreshDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshDriverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1098, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(layout.createSequentialGroup()
                .addGap(452, 452, 452)
                .addComponent(jButtonRefreshDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButtonRefreshDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(202, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRefreshDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshDriverActionPerformed
        // TODO add your handling code here:
        populateTable(dbCon.employeeList(adminId));
    }//GEN-LAST:event_jButtonRefreshDriverActionPerformed
void populateTable(ArrayList<Employee> emp){
        DefaultTableModel model=(DefaultTableModel) jTableDriverAvailibilityStatus.getModel();
        model.setRowCount(0);
        for (Employee e: emp)
        {
            Object[] row =new Object[7];
            row[0]=e.getId();
            row[1]=e.getName();
            row[2]=e.getRole();
            model.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRefreshDriver;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDriverAvailibilityStatus;
    // End of variables declaration//GEN-END:variables
}
