/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license

 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package userInterface.SystemAdminWorkArea;

import Business.Employee.Employee;
import DatabaseUtility.DatabaseHandelLogin;
import javax.swing.JOptionPane;
import userInterface.DoctorRole.DoctorWorkAreaJFrame;
import userInterface.DriverRole.DriverAdminWorkAreaJFrame;
import userInterface.HospitalAdminWorkArea.HospitalAdminWorkAreaJFrame;
import userInterface.NGO.NGOAdminWorkArea;
import userInterface.OPO.OPOAdminWorkArea;
import userInterface.Pathology.PathologyWorkArea;
import userInterface.RecepitionistRole.RecepitionistWorkAreaJFrame;

import userInterface.Transport.TransportLandingPageJFrame;

/**
 *
 * @author anujkumar
 */
public class LoginJPanel extends javax.swing.JFrame {

    /**
     * Creates new form LoginJPanel1
     */
    DatabaseHandelLogin dblogin;
    public LoginJPanel() {
        initComponents();
        addRoles();
        dblogin=new DatabaseHandelLogin();
    }
    public void addRoles(){
        jComboBoxRoles.addItem("SYSTEM ADMIN");
        jComboBoxRoles.addItem("HOSPITAL ADMIN");
        jComboBoxRoles.addItem("DOCTOR");
        jComboBoxRoles.addItem("RECEPTIONIST");
        jComboBoxRoles.addItem("PATHOLOGIST");
        jComboBoxRoles.addItem("NGO ADMIN");
        jComboBoxRoles.addItem("TRANSPORT ADMIN");
        jComboBoxRoles.addItem("OPO ADMIN");
        jComboBoxRoles.addItem("DRIVER");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldUserName = new javax.swing.JTextField();
        jTextFieldPassword = new javax.swing.JTextField();
        jComboBoxRoles = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel3.setText("Role");

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setText("Username");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel2.setText("Password");

        jTextFieldUserName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUserNameActionPerformed(evt);
            }
        });

        jTextFieldPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPasswordActionPerformed(evt);
            }
        });

        jComboBoxRoles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));
        jComboBoxRoles.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jComboBoxRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxRolesActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel5.setText("ORGAN");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/LANDING_PAGE_IMAGE.PNG"))); // NOI18N
        jLabel4.setText("jLabel4");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel6.setText("DONATION");

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("LOGIN");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldUserName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBoxRoles, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(267, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxRoles, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(52, 52, 52)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String username=jTextFieldUserName.getText();
        String password=jTextFieldPassword.getText();
        String role=jComboBoxRoles.getSelectedItem().toString();
        Boolean validation =validateInputFields(username,password);
        if (validation){
            Employee emp;
        switch (role){
            case "SYSTEM ADMIN" -> {
                if ((username.equals("root") && password.equals("root"))){
                    SystemAdminWorkArea JFrame = new SystemAdminWorkArea();
                    JFrame.setVisible(true);
                }
                else{
                    JOptionPane.showMessageDialog(this, "Please check the password");
                }
            }
            case "DOCTOR" -> {
                emp=dblogin.loginUser(username,password,"HOSPITAL_DOCTOR","HOSPITAL");
                if (emp != null){
                    DoctorWorkAreaJFrame JFrame = new DoctorWorkAreaJFrame(emp);
                    JFrame.setVisible(true);  
                }
                else{
                    JOptionPane.showMessageDialog(this, "Please check the username, password and role. ");
                }
            }
            case "HOSPITAL ADMIN" -> {
                emp=dblogin.loginUser(username,password,"HOSPITAL_ADMIN","HOSPITAL");
                if (emp != null){
                    HospitalAdminWorkAreaJFrame JFrame = new HospitalAdminWorkAreaJFrame(emp);
                    JFrame.setVisible(true);  
                }
                else{
                    JOptionPane.showMessageDialog(this, "Please check the username, password and role. ");
                }
            }
            case "RECEPTIONIST" -> {
                emp=dblogin.loginUser(username,password,"HOSPITAL_RECEPTIONIST","HOSPITAL");
                if (emp != null){
                    RecepitionistWorkAreaJFrame JFrame = new RecepitionistWorkAreaJFrame(emp);
                    JFrame.setVisible(true);  
                }
                else{
                    JOptionPane.showMessageDialog(this, "Please check the username, password and role. ");
                }
            }
            case "PATHOLOGIST" -> {
                emp=dblogin.loginUser(username,password,"HOSPITAL_PATHOLOGIST","HOSPITAL");
                if (emp != null){
                    PathologyWorkArea JFrame = new PathologyWorkArea(emp);
                    JFrame.setVisible(true);  
                }
                else{
                    JOptionPane.showMessageDialog(this, "Please check the username, password and role. ");
                }
            }
            case "NGO ADMIN" -> {
                emp=dblogin.loginUser(username,password,"NGO_ADMIN","NGO");
                if (emp != null){
                    NGOAdminWorkArea JFrame = new NGOAdminWorkArea(emp);
                    JFrame.setVisible(true);  
                }
                else{
                    JOptionPane.showMessageDialog(this, "Please check the username, password and role. ");
                }
            }
            case "TRANSPORT ADMIN" -> {
                emp=dblogin.loginUser(username,password,"TRANSPORT_ADMIN","TRANSPORT");
                if (emp != null){
                    TransportLandingPageJFrame JFrame = new TransportLandingPageJFrame(emp);
                    JFrame.setVisible(true);  
                }
                else{
                    JOptionPane.showMessageDialog(this, "Please check the username, password and role. ");
                }
            }
            case "OPO ADMIN" -> {
                emp=dblogin.loginUser(username,password,"OPO_ADMIN","OPO");
                if (emp != null){
                    OPOAdminWorkArea JFrame = new OPOAdminWorkArea(emp);
                    JFrame.setVisible(true);  
                }
                else{
                    JOptionPane.showMessageDialog(this, "Please check the username, password and role. ");
                }
            }
            case "DRIVER" -> {
                emp=dblogin.loginUser(username,password,"TRANSPORT_DRIVER","TRANSPORT");
                if (emp != null){
                    DriverAdminWorkAreaJFrame JFrame = new DriverAdminWorkAreaJFrame(emp);
                    JFrame.setVisible(true);  
                }
                else{
                    JOptionPane.showMessageDialog(this, "Please check the username, password and role. ");
                }
            }
        }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUserNameActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jTextFieldUserNameActionPerformed

    private void jTextFieldPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPasswordActionPerformed

    private void jComboBoxRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxRolesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxRolesActionPerformed
private Boolean validateInputFields(String userName,String password) {
        //Function to validate the input fields
        Boolean validated=true;
        if(userName == null || userName.isEmpty()){
            JOptionPane.showMessageDialog(this,"Username cannot be empty");
            validated=false;
        }
        else if(password == null || password.isEmpty()){
            JOptionPane.showMessageDialog(this,"Password cannot be empty.");
            validated=false;
        }
        return validated;
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginJPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginJPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginJPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginJPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginJPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxRoles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldPassword;
    private javax.swing.JTextField jTextFieldUserName;
    // End of variables declaration//GEN-END:variables
}
