/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package userInterface.SystemAdminWorkArea;

/**
 *
 * @author Lenovo
 */
public class SystemAdminWorkAreaJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public SystemAdminWorkAreaJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitAdminWorkArea = new javax.swing.JSplitPane();
        AdminWorkAreaPanel1 = new javax.swing.JPanel();
        ManageHospitalJButton = new javax.swing.JButton();
        ManageOPOJButton = new javax.swing.JButton();
        ManageTransportJButton = new javax.swing.JButton();
        ManageNGOJButton = new javax.swing.JButton();
        AdminWorkAreaPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitAdminWorkArea.setDividerLocation(180);
        jSplitAdminWorkArea.setMinimumSize(new java.awt.Dimension(100, 100));
        jSplitAdminWorkArea.setPreferredSize(new java.awt.Dimension(185, 50));

        AdminWorkAreaPanel1.setBackground(new java.awt.Color(204, 0, 204));
        AdminWorkAreaPanel1.setOpaque(false);

        ManageHospitalJButton.setBackground(new java.awt.Color(255, 0, 51));
        ManageHospitalJButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ManageHospitalJButton.setForeground(new java.awt.Color(255, 255, 255));
        ManageHospitalJButton.setText("MANAGE HOSPITAL");

        ManageOPOJButton.setBackground(new java.awt.Color(255, 0, 51));
        ManageOPOJButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ManageOPOJButton.setForeground(new java.awt.Color(255, 255, 255));
        ManageOPOJButton.setText("MANAGE OPO");

        ManageTransportJButton.setBackground(new java.awt.Color(255, 0, 51));
        ManageTransportJButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ManageTransportJButton.setForeground(new java.awt.Color(255, 255, 255));
        ManageTransportJButton.setText("MANAGE TRANSPORT");

        ManageNGOJButton.setBackground(new java.awt.Color(255, 0, 51));
        ManageNGOJButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ManageNGOJButton.setForeground(new java.awt.Color(255, 255, 255));
        ManageNGOJButton.setText("MANAGE NGO");

        javax.swing.GroupLayout AdminWorkAreaPanel1Layout = new javax.swing.GroupLayout(AdminWorkAreaPanel1);
        AdminWorkAreaPanel1.setLayout(AdminWorkAreaPanel1Layout);
        AdminWorkAreaPanel1Layout.setHorizontalGroup(
            AdminWorkAreaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminWorkAreaPanel1Layout.createSequentialGroup()
                .addGroup(AdminWorkAreaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ManageTransportJButton)
                    .addComponent(ManageNGOJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ManageOPOJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ManageHospitalJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AdminWorkAreaPanel1Layout.setVerticalGroup(
            AdminWorkAreaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminWorkAreaPanel1Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(ManageHospitalJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ManageOPOJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ManageNGOJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ManageTransportJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );

        jSplitAdminWorkArea.setLeftComponent(AdminWorkAreaPanel1);

        AdminWorkAreaPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout AdminWorkAreaPanel2Layout = new javax.swing.GroupLayout(AdminWorkAreaPanel2);
        AdminWorkAreaPanel2.setLayout(AdminWorkAreaPanel2Layout);
        AdminWorkAreaPanel2Layout.setHorizontalGroup(
            AdminWorkAreaPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 527, Short.MAX_VALUE)
        );
        AdminWorkAreaPanel2Layout.setVerticalGroup(
            AdminWorkAreaPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 468, Short.MAX_VALUE)
        );

        jSplitAdminWorkArea.setRightComponent(AdminWorkAreaPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jSplitAdminWorkArea, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSplitAdminWorkArea, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SystemAdminWorkAreaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SystemAdminWorkAreaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SystemAdminWorkAreaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SystemAdminWorkAreaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SystemAdminWorkAreaJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminWorkAreaPanel1;
    private javax.swing.JPanel AdminWorkAreaPanel2;
    private javax.swing.JButton ManageHospitalJButton;
    private javax.swing.JButton ManageNGOJButton;
    private javax.swing.JButton ManageOPOJButton;
    private javax.swing.JButton ManageTransportJButton;
    private javax.swing.JButton jButtonHospitalEnterpriseLogin;
    private javax.swing.JButton jButtonNGOEnterpriseLogin;
    private javax.swing.JButton jButtonOPOAdminLogin;
    private javax.swing.JButton jButtonTransportEnterpriseLogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitAdminWorkArea;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
